### ISSUE TITLE
Enable mypy typechecker tracker

### ISSUE THREAD

**Issue by mergennachin** [pytorch/executorch#7441]
### 🚀 The feature, motivation and pitch

Currently there's no python typechecker enabled on OSS. Let's enable mypy gradually

### Alternatives

Another alternative is to use pyre. But we want to be consistent with pytorch/pytorch which uses mypy.

### Additional context

Progress: 

- [ ] exir
- [ ] backends
- [ ] examples
- [ ] extension
- [ ] devtools
- [x] test https://github.com/pytorch/executorch/pull/7497
- [x] util https://github.com/pytorch/executorch/pull/7496
- [x] scripts https://github.com/pytorch/executorch/pull/7442
- [x] profiler https://github.com/pytorch/executorch/pull/7494
- [x] docs https://github.com/pytorch/executorch/pull/7493
- [x] codegen  https://github.com/pytorch/executorch/pull/7493

**Comment by mergennachin** [comment]
https://github.com/pytorch/executorch/pull/7776

**Comment by robert-kalmar** [comment]
backend/nxp - Issue here https://github.com/pytorch/executorch/issues/13518
